### ISSUE TITLE
Data App (Service) URL change unexpectedly

### ISSUE THREAD

**Issue by allansene** [dadosfera/Bugsfera#47]
##### There are customers are directly impacted by this bug? Which?
dadosferademo and mapa-avaliaçoes (still on PoC)

-------------------------------------------

#### Bug Category
- [ ] Connection Manager
- [ ] Connection Test
- [ ] Creating Pipeline
- [ ] Executing Pipeline
- [ ] Cataloging Data Asset
- [x] Other

##### Describe the bug
Orchest changes the Service URL unexpectedly then Data App embedding does not work (redirects to Projects page) 

##### To Reproduce
It is happening intermittently. 

Last time we have had exposed this link to the client: https://app-intelligence-dadosferademo.dadosfera.ai/pbp-service-streamlit-615a4197-5473-4dbe42e19b2a-5564-420c_8501/

Then it changed to https://app-intelligence-dadosferademo.dadosfera.ai/pbp-service-data-app-33d5abf6-9933-4c82135c2fef-7e24-41df_8501/

We are exposing this type of Data Assets on LPs like this:
https://mapa-data-app.umso.co/

##### Expected behavior
-------------------------------------------
It is supposed to stay with the same link, like Metabase's Public Embedded 

##### Screenshots
-------------------------------------------

##### This bug impact any demo or a sales?
-------------------------------------------
Yes - Mapa Avaliacoes

#### Dadosfera Customer:
-------------------------------------------

&nbsp;

## Other informations:

**Any logs, error output, etc?** …

What environment of software are you using?
- [ ] PRD
- [ ] Other

**Browser Engine and Version:** …

**When the bug happened:** …

**Comment by rafaelsantanaep** [comment]
Hi Allan, this is not a bug. Actually, the new endpoint is: https://app-intelligence-dadosferademo.dadosfera.ai/pbp-service-data-app-615a4197-5473-4dbe42e19b2a-5564-420c_8501/

This change occurred because the service name was renamed.

The service endpoint provided by Dadosfera Intelligence follows the following pattern: `{base_url}/phb-service-{service_name}-{project_id}_{port}`

If one of those changes, the URL will change, therefore, for now at least, I think we should not change either of them for services that are in `production`. And if a change is required, we should have mapped every place a data app is embedded to propagate the new URL.
