### ISSUE TITLE
Analyzes of LOGs in the Dadosfera are being identical

### ISSUE THREAD

**Issue by mariaeduaruda** [dadosfera/Bugsfera#58]
##### There are customers are directly impacted by this bug? Which?
Elvenworks

#### Bug Category
- [ ] Connection Manager
- [ ] Connection Test
- [ ] Creating Pipeline
- [ ] Executing Pipeline
- [ ] Cataloging Data Asset
- [x] Other

##### Describe the bug
Some synchronizations the status of the platform identifies a failure in the process, however when we analyze the LOGs, both are completely identical, making it impossible to identify what may have happened.

##### Screenshots
![image](https://user-images.githubusercontent.com/87451133/212756461-2d48964d-3d0a-4fcf-9627-e2b1b10dbc93.png)

##### This bug impact any demo or a sales?
Yes.

#### Dadosfera Customer:
Dadosfera

&nbsp;

What environment of software are you using?
- [x] PRD
- [ ] Other

**Comment by rafaelsantanaep** [comment]
This may be a problem in the step that turns off the snowflake warehouse. Let me check.

**Comment by rafaelsantanaep** [comment]
![image](https://user-images.githubusercontent.com/40280691/212759920-81f4b42d-5e19-46c2-adff-32e00306e545.png)
É isso mesmo, é um problema de condição de corrida, a dag tentou desligar o warehouse do snowflake, mas ele já tinha sido desligado por uma outra dag / processo que estava rodando de maneira concorrente.  Não houve problema na execução dos jobs, por conta disso, o log é identico.

**Comment by mariaeduaruda** [comment]
@rafaelsantanaep Thanks for answering me, I'll return this to Elven!

**Comment by cicerojmm** [comment]
@rafaelsantanaep 
I understand that the error was from an internal process of ours, let's say, which is to finish the snowflake section, but for the client it shows in the interface that there was an error and so he checked the logs and there was no error in the logs, due to the fact that the product does not expose this type of error?
Would the best scenario be to show the client there was an internal error?
Or not show error to the client because the data was successfully written?

FY @beatrizaantunes

**Comment by rafaelsantanaep** [comment]
@cicerojmm The main problem is that our logic to see if a pipeline was successful depends on the last `node` of airflow, which is the step to turn off the dag.

There are two potential solutions:
- Pipeline succeeds when all jobs are successful, ignoring any other steps that may come later (like this step to turn off the warehouse).
- Remove this step from the pipelines since the warehouse will be automatically turned off when after 1 minute of ociosity. This may impact a little bit our costs.
